package com.jacob.patton.bereaconvo;

import java.util.ArrayList;
import java.util.List;


public class DataStored {
	//Master database
	public List<String[]> database;
	
	
	public List<String[]> createdata(){
		//[ID,semester, date,time, title,speaker,description,attended]
		
		//ID = Should be a different number for each one!
		//semester = needs to be "Fall" or "Spring" (capital F and S).
		// Attended - NOT included in this list, only when merged with the MainActivity. Later would be important for a database. 
		
		 database = new ArrayList<String[]>();
		 //2013-2014 convos
		 
		 /*
		  * Any new convos must be added to the end of the list to keep the "StoredAttendance" string in the correct order. 
		  * If the app version in Strings.xml data file is changed, it will clear the "StoredAttendance" string.  
		 */
		 
		 //database.add(new String[]{"ID","Semester","Date","Time","title","presenter","description"});
		 database.add(new String[]{"1","Fall","08/29/2013","4:00pm","Community and Commitments","Dr. Lyle Roelofs","President Roelofs, Berea’s Ninth President, will open the academic year with his reflections for the entire Berea College Community, followed by comments from a faculty member, staff member, student, and alum. Campus musical groups will also perform."});
		 database.add(new String[]{"2","Fall","09/05/2013","3:00pm","Looking for Dragons: Odonata Research in the Genomics Age","Dr. Jessica Ware"," An evolutionary biologist at Rutgers University, Dr. Ware studies flight patterns, migration, mating, and predatory behavior of insects and the effects of changing biodiversity on their lives. One of her areas of specialization is the biogeography of dragonflies and damselflies."});
		 database.add(new String[]{"3","Fall","09/12/2013","8:00pm","A Dave Brubeck Tribute","Brubeck Brothers Quartet","The talented brothers—Dan, master of complex rhythms on drums, and Chris, multiinstrumentalist on electric bass and bass trombone—lead the BBQ’s triumphant meeting of improvisation and composed music. Joined by piano and guitar, the quartet effortlessly combines the genres of straight-ahead jazz, funk, blues, and the Brubeck tradition of playing in odd time signatures."});
		 database.add(new String[]{"4","Fall","09/19/2013","3:00pm","Hills, Humanity, Holiness: A Conversation on Culture, Race, and Religion","Three Center Directors","Dr. Alicestyne Turley (Carter G. Woodson Center CGWC), Dr. Chris Green (Loyal Jones Appalachian Center-LJAC) and Rev. Gail Bowman (Willis D. Weatherford Campus Christian Center-CCC) present a shared conversation about this College’s search for common ground as a basis for celebrating community. Joe Saleem, II, ’08, Residential Life Collegium, MC."});
		 database.add(new String[]{"5","Fall","10/03/2013","3:00pm","Pioneer in Women’s Education","Jane B. Stephenson","Jane B. Stephenson, wife of former Berea College President John Stephenson, founded the New Opportunity School for Women in 1987 to improve the educational, financial, and personal circumstances of low-income Appalachian women. The development and impact of this innovative program, which won the Oprah Show’s “Use Your Life Award,” will be discussed by Stephenson, enhanced with photography by her son David Stephenson and a performance by the Women’s Choir."});
		 database.add(new String[]{"6","Fall","10/10/2013","3:00pm","America’s Global Challenges","Nicholas Burns","Currently the Sultan of Oman Professor of International Relations and the Practice of Diplomacy at the Harvard Kennedy School of Government, Dr. Burns served in the U. S. Government for 27 years as a Foreign Service officer in Russia, India, Greece, and countries of Africa and the Middle East. Burns, who is a regular guest on MSNBC, CNN, NPR, and PBS, will bring a rare level of insight and a unique perspective on the complex international issues facing the U.S. Co-sponsored with Political Science."});
		 database.add(new String[]{"7","Fall","10/17/2013","8:00pm","Hot Jazz and Western Swing","Hot Club Of Cow Town","This dynamic trio’s name alludes to the hot jazz playing of Django Reinhardt and Stéphane Grappelli in the legendary Quintet of the Hot Club of France, and to the fiddle tunes and cowboy songs which are also central to their tight, driving ensemble sound."});
		 database.add(new String[]{"8","Fall","10/24/2013","3:00pm","The Night Sky","Dr. Derrick Pitts","Selected as one of the 50 most important African Americans in Research Science by Science Spectrum, Dr. Pitts is the Chief Astronomer and Planetarium Director for the Franklin Institute Science Museum in Philadelphia, a NASA Solar System Ambassador, and radio host of “Sky Talk” on Public Radio. His captivating talks spark interest in astronomy and curiosity about science."});
		 database.add(new String[]{"9","Fall","10/30/2013","*8:00pm","Count Dracula","Theatre Laboratory","Directed by Shan R. Ayers. Tickets required. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups."});
		 database.add(new String[]{"10","Fall","10/31/2013","3:00pm","From Mathematics to Sculpture","Dr. George Hart","An interdisciplinary sculptor/designer, mathematician, computer scientist, and educator, Hart is cofounder of North America’s only Museum of Mathematics, where he set the “Math is Cool!” tone of the museum and designed original exhibits and workshop activities which use art-related ways to engage students in thinking mathematically. His research explores innovative ways to use computer technology to design artwork, and his videos reveal the fun and creative sides of mathematics."});
		 database.add(new String[]{"11","Fall","11/01/2013","*8:00pm","Count Dracula","Theatre Laboratory","Directed by Shan R. Ayers. Tickets required.\n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. "});
		 database.add(new String[]{"12","Fall","11/07/2013","3:00pm","Woody Fest: The Life, Time, & Music of Woody Guthrie","Jake Speed","Cincinnati musician and educator Jake Speed, known as “the Queen City’s favorite troubadour,” honors the American folk music legend Woody Guthrie in this concert. Speed “sings, picks guitar, blows harmonica, buzzes kazoo, and kicks the beat on the washboard,” as he performs Guthrie’s songs about the Dust Bowl era of the 1930s."});
		 database.add(new String[]{"13","Fall","11/14/2013","8:00pm","Blizzard Drums","Fubuki Daiko","In ancient Japan, Taiko drums were used to frighten invaders, inspire troops in battle, and call the gods. For the past 18 years, this spirited group has catapulted Japanese Taiko drumming into the 21st century with an eclectic experience that is part martial arts athleticism, part dance, and all rhythm."});
		 database.add(new String[]{"14","Fall","11/21/2013","3:00pm","Giving Voice to the Voiceless","Enrique Morones","Immigration is one of the most hotly debated issues of our time. Internationally acclaimed human rights activist and fearless defender of immigrants and undocumented aliens, Morones is a committed Christian who founded Border Angels to save peoples’ lives at desolate border crossings. He brings to the forefront stories of those often forgotten in the fight for social justice."});
		 database.add(new String[]{"15","Spring","01/20/2014","3:00pm","Our Shared Humanity: Creating Understanding Through the Principles of MLK","Nontombi Naomi Tutu","Currently the Program Coordinator for the Race Relations Institute at Fisk University, Tutu was raised in apartheid South Africa, child of Archbishop Desmond Tutu and Nomalizo Leah Tutu. Combining Dr. King’s dream of the “Beloved Community” with the teachings of a South African proverb, Tutu encourages us to focus on our shared humanity and to concentrate on what we have the power to change in order to build a just world."});
		 database.add(new String[]{"16","Spring","01/23/2014","3:00pm","Blair Pathways: A Musical Explanation of America’s Largest Labor Uprising Project","Saro Lynch-Thomason","Award-winning ballad singer and folklorist Saro LynchThomason is the producer of this multi-media project which uses music and narrative to tell the story of the West Virginia mine wars of 1900-1921."});
		 database.add(new String[]{"17","Spring","01/30/2014","3:00pm","Cuba: An Endearing Part of U.S. History","Dr. Alan McPherson","Associate Professor of International and Latin American Studies at the University of Oklahoma, McPherson will discuss social, economic and political connections between the U. S. and Cuba. A frequent media commentator, he has authored or edited 4 books on U.S.-Latin American relations and is currently finishing a book on Latin American resistance to U.S. military occupations."});
		 database.add(new String[]{"18","Spring","02/06/2014","3:00pm","Civic Nationalism in the Late 19th Century","Dr. Daryl Michael Scott","Professor of History at Howard University, Dr. Scott discovered a lost manuscript by Carter G. Woodson. He is editor of the Woodson Review and a prominent historian of African-American History, Southern history, and black-white relationships since the Civil War."});
		 database.add(new String[]{"19","Spring","02/13/2014","8:00pm","Langston Hughes Project: Poetry, Jazz, and the Struggle for Freedom","Ron McCurdy Jazz Quartet","This concert is a multi-media performance of Hughes’ kaleidoscopic jazz poem suite, “Ask Your Mama: Twelve Moods for Jazz.” Hughes’ homage in verse and music to the struggle for artistic and social freedom at home and abroad at the beginning of the 1960s is linked to images of people and places from slavery to the Harlem Renaissance to the Civil Rights Movement."});
		 database.add(new String[]{"20","Spring","02/19/2014","*8:00pm","Fefu and Her Friends","Theatre Laboratory","Directed by Adanma O. Barton. Tickets required.\n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. "});
		 database.add(new String[]{"21","Spring","02/20/2014","3:00pm","Overcoming Obstacles and Making History","David Paterson","A life-long governmental and political figure, Paterson became the youngest state senator in New York’s history when he was elected to represent Harlem, and later he became the state’s first African-American legislative leader. In 2007, he was the state’s first AfricanAmerican lieutenant governor and, in 2008, its first African-American governor. Blinded in childhood, he is an out-spoken advocate for the American Foundation for the Blind."});
		 database.add(new String[]{"22","Spring","02/21/2014","*8:00pm","Fefu and Her Friends","Theatre Laboratory","Directed by Adanma O. Barton. Tickets required. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups."});
		 database.add(new String[]{"23","Spring","02/27/2014","3:00pm","A World in Need of Healing: Peacemakers from Mandela to Asad","John Yearwood","In his work as World Editor of the Miami Herald, a position he has held since 2003, award-winning journalist Yearwood travels extensively directing the paper’s coverage of the most pressing global issues of our time. Based on his quarter century of journalism, he will discuss ways in which understanding may be enhanced and peace fostered."});
		 database.add(new String[]{"24","Spring","03/13/2014","8:00pm","Middle-Eastern Instrumentation and World Beat Fusion","Pharaoh’s Daughter","Charismatic singer-songwriter and multi-instrumentalist Basya Schechter leads her stellar group of musicians through swirling Hasidic chants and Mizrachi and Sephardi folk-rock, blending traditional Middle Eastern and Judaic melodies with Arabic and African rhythms."});
		 database.add(new String[]{"25","Spring","03/19/2014","*8:00pm","Country Dancers Performance","Berea College Country Dancers","Directed by Deborah Thompson. Old Seabury Gym. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. \n\nDates for musical ensemble performances are subject to change. See announcements on campus bulletin boards or the convocations website to confirm the place, date and time of the performance."});
		 database.add(new String[]{"26","Spring","03/20/2014","3:00pm","Journey to Women’s Leadership","Judge Nancy Gertner","Former U.S. Federal Judge, Professor at Harvard Law School, and author of In Defense of Women, Dr. Gertner discusses her professional life as an “unrepentant advocate” for women’s rights and civil liberties."});
		 database.add(new String[]{"27","Spring","03/23/2014","*3:00pm","BME Spring Concert","Black Music Ensemble","Directed by Kathy Bullock. Berea Baptist Church. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. \n\nDates for musical ensemble performances are subject to change. See announcements on campus bulletin boards or the convocations website to confirm the place, date and time of the performance."});
		 database.add(new String[]{"28","Spring","03/27/2014","3:00pm","Green Jobs for Native Americans","Henry Red Cloud","A 21st Century Lakota warrior, Red Cloud was born and raised on the Pine Ridge Reservation in South Dakota. Through his family-scale renewable energy enterprises, he is providing his people with a new vision for the future while maintaining their traditions, cultural heritage, and deep connection to Mother Earth."});
		 database.add(new String[]{"29","Spring","03/28/2014","*8:00pm","Kinetic Expressions ’14","Modern Dance","Directed by Sarah Downs. Seabury Arena. Tickets required.\n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. \n\nDates for musical ensemble performances are subject to change. See announcements on campus bulletin boards or the convocations website to confirm the place, date and time of the performance."});
		 database.add(new String[]{"30","Spring","03/29/2014","*8:00pm","Kinetic Expressions ’14","Modern Dance","Directed by Sarah Downs. Seabury Arena. Tickets required. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. \n\nDates for musical ensemble performances are subject to change. See announcements on campus bulletin boards or the convocations website to confirm the place, date and time of the performance."});
		 database.add(new String[]{"31","Spring","04/03/2014","3:00pm","Higher Ground in Harlan County","Robert Gipe","Director of the Appalachian Program at Southeast Kentucky Community & Technical College, Gipe brings cast members of the community theater project Higher Ground to perform selected songs and scenes. Performed with local actors and music, their plays draw from oral histories to deal with issues affecting youth in today’s Appalachian coalfields."});
		 database.add(new String[]{"32","Spring","04/05/2014","*8:00pm","Spring Concert","Concert Choir and Chamber Singers","Directed by Stephen C. Bolster. Gray Auditorium.\n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. \n\nDates for musical ensemble performances are subject to change. See announcements on campus bulletin boards or the convocations website to confirm the place, date and time of the performance."});
		 database.add(new String[]{"33","Spring","04/06/2014","*3:00pm","Spring Concert","Concert Choir and Chamber Singers","Directed by Stephen C. Bolster. Gray Auditorium\n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. \n\nDates for musical ensemble performances are subject to change. See announcements on campus bulletin boards or the convocations website to confirm the place, date and time of the performance."});
		 database.add(new String[]{"34","Spring","04/10/2014","8:00pm","The Mystical Arts of Tibet","Tibetan Monks of Drepung Loseling Monastery","Playing traditional Tibetan instruments, these multiphonic singers will perform ancient temple music and dances for world healing. During the week of April 7-11, the monks will create a Tantric Buddhist mandala sand painting in Baird Lounge. These paintings are painstakingly poured grain by grain to generate energies for global healing."});
		 database.add(new String[]{"35","Spring","04/12/2014","*8:00pm","Bluegrass Ensemble Spring Concert","Berea College Bluegrass Ensemble","Directed by Al White. Gray Auditorium. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. \n\nDates for musical ensemble performances are subject to change. See announcements on campus bulletin boards or the convocations website to confirm the place, date and time of the performance."});
		 database.add(new String[]{"36","Spring","04/15/2014","*7:30pm","Wind & Jazz Spring Concert","Wind & Jazz Ensembles","Directed by Matthew Talbert. Gray Auditorium. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. \n\nDates for musical ensemble performances are subject to change. See announcements on campus bulletin boards or the convocations website to confirm the place, date and time of the performance."});
		 database.add(new String[]{"37","Spring","04/16/2014","*8:00pm","Jesus Christ Superstar","Theatre Laboratory","Directed by Deborah Martin. Tickets required. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. "});
		 database.add(new String[]{"38","Spring","04/17/2014","*8:00pm","Jesus Christ Superstar","Theatre Laboratory","Directed by Deborah Martin. Tickets required. \n\nA student can receive up to a total of three convocation credits during the academic year for attending one theatre event, one musical event, and one dance event chosen from among the following seven groups. "});

			
			// returns the above list. 			
			return database;
	}
	
	


}