package com.jacob.patton.bereaconvo;

import java.util.ArrayList;
import java.util.List;


public class DataStored {
	//Master database
	public List<String[]> database;
	
	
	public List<String[]> createdata(){
		//[ID,semester, date,time, title,speaker,description,attended]
		
		//ID = Should be a different number for each one!
		//semester = needs to be "Fall" or "Spring" (capital F and S).
		// Attended - NOT included in this list, only when merged with the MainActivity. Later would be important for a database. 
		
		 database = new ArrayList<String[]>();
		 		// Fall 2012 convos
				database.add(new String[]{"1","Fall","08/30/12","3:00pm","Why Berea?" ,"Speaker: Dr. Lyle Roelofs","President Roelofs, Berea’s Ninth President, opens the new academic year as he shares hisideas about Berea College in the past and in the 21st Century. Welcome to our new President!."});
				database.add(new String[]{"2","Fall","09/06/12","3:00pm","Tuning the Planet: Are We Listening?" ,"Speaker: Michael Fitzpatrick","Pioneering cellist and electric cellist, recording artist, composer, producer, and filmmaker Michael Fitzpatrick will share in narrative, images, and live musical performance the genesis of Tuning the Planet, the musical-consciousness convergence project inspired by the friendship of His Holiness, The Dalai Lama, and Thomas Merton, recorded and filmed inside Mammoth Cave. Supported by the Stephenson Memorial Concert Fund."});
				database.add(new String[]{"3","Fall","09/13/13","8:00pm","Diversity Unparalleled","Performers: California Guitar Trio","Founded in 1991, this trio of innovative guitarists interprets a diverse range of instrumental styles, from European classical music to rock, blues, jazz, world music, and even surf music in their concerts and 14 CDs. A Stephenson Memorial Concert"});
				database.add(new String[]{"4","Fall","09/20/12","3:00pm","Obedience and Action" ,"Speaker: Sister Joan Chittister","Courageous, passionate, and charged with energy, Sister Joan Chittister is one of the most articulate analysts and influential religious leaders of our age. An international lecturer and author of more than 45 books, she is Executive Director of Benetvision, a spiritual resource and research center, and Co-Chair of the Global Peace Initiative of Women, facilitating a world-wide network of women peace builders. Sponsored by the Willis D. Weatherford Jr. Campus Christian Center (CCC). Robbins Peace Lecture."});
				database.add(new String[]{"5","Fall","09/27/12","3:00pm","How to Fall in Love with the World…in Spite of History", "Speaker: Matthew Fox","An internationally acclaimed spiritual theologian, author of thirty books, Episcopal priest, and activist who was a member of the Dominican Order for 34 years, Matthew Fox has been renewing the ancient mystical tradition of Creation Spirituality. Co-sponsored with Women’s and Gender Studies."});
				database.add(new String[]{"6","Fall","10/04/13","3:00pm","A.A. Burleigh: The Long Climb to Freedom", "Event: Founders’ Day Convocation","This convocation will celebrate Berea’s interracial history with a living history performance by Hasan Davis, ’92, who is a community activist, youth advocate, lawyer, motivational speaker, poet, and actor. Davis will portray Angus A. Burleigh, a soldier in the Union Army stationed at Camp Nelson and an early African-American graduate of Berea College (1875). Burleigh’s story is a testament to the unconquerable spirit of humanity."});
				database.add(new String[]{"7","Fall","10/18/13","8:00pm","Renegade Retro Band", "Performers: Sweetback Sisters","All talented instrumentalists and vocal harmonizers, the Sweetback Sisters (a band of 2 women and 4 men) model their songs after vintage country music and western swing, infusing their throwback sound with youthful intensity and broad influences. A Stephenson Memorial Concert."});
				database.add(new String[]{"8","Fall","10/25/13","3:00pm","The Skills Problem.", "Speaker: Dr. James Heckman","Director of the Economics Research Center and Henry Schultz Distinguished Service Professor of Economics at the University of Chicago, Dr. Heckman shared the Nobel Prize in Economic Science in 2000. His research is rooted in economics but goes well outside of traditional analyses to integrate research in psychology, neuroscience, and biology. Co-sponsored with Economics and Business."});
				database.add(new String[]{"9","Fall","11/01/13","3:00pm","Emergency.", "Speaker: Daniel Beaty","Daniel Beaty is an award-winning actor, singer,writer, and composer whose performance of Emergency won the 2007 Obie Award for Excellence in Off-Broadway Theater. In this explosive solo tour de force featuring slam poetry, multi-character transformation, and song, Beaty portrays a cast of 40 characters who respond to the surreal emergence of a slave ship in front of the Statue of Liberty—creating a stirring commentary on what it is to be human and the longing to be free. Co-sponsored with the Office of the Academic Vice President and Dean of the Faculty, the Black Cultural Center (BCC) & African and African-American Studies (AAAS)."});
				database.add(new String[]{"10","Fall","11/08/13","8:00pm","Innovative Chamber Music.", "Performers:American Chamber Players ","Led by violinist and NPR commentator Miles Hoffman, this stellar group of musicians invariably play an imaginative program with impeccable phrasing and attention to dynamics. Their repertoire ranges from familiar masterpieces to neglected gems to newly commissioned American works. A Stephenson Memorial Concert."});
				database.add(new String[]{"11","Fall","11/15/13","3:00pm","Ballads on an Appalachian Evening", "Speaker: Nikki Giovanni","Poet, activist, mother, and distinguished Professor of English at Virginia Tech, Nikki Giovanni is author of 27 books and five time NAACP Image Award winner. In a career that has earned her accolades, awards, and honorary degrees, she has established herself as an outspoken and passionate writer who can entertain and challenge, inform and inspire. Co-sponsored with the Loyal Jones Appalachian Center (LJAC)."});
				database.add(new String[]{"12","Fall","11/25/13","3:00pm","The Moral Underground: How Ordinary People Subvert an Unfair Economy.", "Speaker: Dr. Lisa Dodson","A leading voice on low wage work and family issues, Boston College Sociology Professor Lisa Dodson follows the principle of “research as democracy,” bringing to light a silent movement for economic justice and the lives of people whose voices are seldom heard in national debate. Her current focus is the family effects of a deeply stratified economy that is undermining working families and the larger society. Co-Sponsored with Division III."});
				
				// Spring 2013 convos
				database.add(new String[]{"13","Spring","01/21/13","3:00pm","Never Turning Back: How Do We Know When We’ve Won. ", "Speaker:Jim Kates","After his freshman year at Wesleyan U, Jim Kates volunteered for the Mississippi Summer Project, assisting in voter registration, and later became a non-violence trainer and public school teacher. Also a poet, he currently co-directs the non-profit Zephyr Press, which has featured literary works on the civil rights movement. Co-sponsored with the BCC, AAAS, CCC, and the Office of the President. Martin Luther King Jr. Memorial Convocation."});
				database.add(new String[]{"14","Spring","01/24/13","3:00pm","Lessons from Abroad: The Opportunities of a Borderless World","Speaker: Richard Heinzl, M.D.","Medical doctor and founder of the Canadian chapter of the Nobel Prize winning organization Doctors Without Borders, Dr. Heinzl is passionately committed to providing healthcare around the globe to people in crisis. His talk takes us past the expected sphere of humanitarian aid stories to reveal a world of remarkable universal lessons and incredible human stories. Co-sponsored with Nursing"});
				database.add(new String[]{"15","Spring","01/31/13","3:00pm","The Death and Life and Death of Presidential Government.","Speaker:Dr. Theodore Lowi","One of the most influential political scholars of the modern era, with a focus on American political thought and government, Dr. Lowi is currently the John L. Senior Professor of American Institutions at Cornell University. He is a frequent guest on NPR, PBS, and cable television news talk shows, and his provocative essays appear frequently in The New York Times. Co sponsored with Political Science. Begley-Van Cleve Lecture"});
				database.add(new String[]{"16","Spring","02/07/13","8:00pm","Spreading African Spirit Through Song.","Performer: Vusi Mahlasela","Known as “the voice” in his home country, world-acclaimed singer, composer, and guitarist Vusi Mahlasela is celebrated for his poetic, optimistic lyrics of freedom, reconciliation, and compassion. His band’s performances bridge generations and continents and connect apartheidscarred South Africa with its future promise. A Stephenson Memorial Concert."});
				database.add(new String[]{"17","Spring","02/14/13","3:00pm","Ties That Bind: African American and Native American Interrelations.","Speaker: Dr. Tiya Miles","Awarded a 2011 MacArthur Foundation Fellowship for her work on African American and Native American history, Dr. Miles is a professor in American Culture, History, Afro-American & African Studies, and Native American Studies at the University of Michigan. She is also founder of ECO Girls, an environmental and cultural organization for girls in urban Southeast Michigan. Co sponsored with BCC, AAAS, and the CCC. Carter G. Woodson Memorial Convocation."});
				database.add(new String[]{"18","Spring","02/21/13","3:00pm","At the Crossroads of Art and Science.","Speaker: Dr. Alan Lightman","Both a distinguished physicist and an accomplished novelist, MIT Professor Alan Lightman has made fundamental contributions to the theory of astrophysical processes. In addition to research and publication in physics, astrophysics, astronomy, science education, and the philosophy of science, he has written novels about scientific discoveries and their discoverers, including his international best-seller, Einstein’s Dreams. Berea College Science Lecture"});
				database.add(new String[]{"19","Spring","02/28/13","3:00pm","Making Peace with the Earth.","Speaker:Dr. Vandana Shiva","Dr. Shiva, physicist and internationally renowned activist for biodiversity, presents the fundamental connection between human rights and the protection of the environment and offers solutions to critical problems posed by the effects of globalization and climate change on the poorest and most populous nations. Co-sponsored with Women’s and Gender Studies."});
				database.add(new String[]{"20","Spring","03/07/13","3:00pm","Leaps and Bounds","Speaker: Tevyn East","Choreographed and performed by Tevyn East, this one-woman show weaves Biblical and personal narratives, song, dance, and prayer to explore intersections between faith, ecology, and the global economy. Her performance inspires Christians to articulate a faith response to our current ecological and economic crises and awakens our imaginations to new ways of relating to Earth. Presented as part of the activities of the Accent on Christian Faith Week, sponsored by the CCC."});
				database.add(new String[]{"21","Spring","03/21/13","8:00pm","Magical Music from Ireland.","Performers: Dervish","Magical Music from Ireland. Dervish has brought traditional Irish music from County Sligo to every corner of the globe. Each concert brings high energy instrumentation, beautifully measured ballads, charming lyrics, inspiring melodies, and ultra-sweet vocals that lift audiences from their seats. A Stephenson Memorial Concert."});
				database.add(new String[]{"22","Spring","04/04/13","3:00pm","Tell the Truth but Tell it Slant: The Past as Present in Appalachia.","Speaker: Ron Rash","The Parris Distinguished Professor of Appalachian Cultural Studies at Western Carolina University, Ron Rash has published 5 novels, 5 short story collections and 4 books of poetry. In his poetry and stories of loss and redemption, his love of family and a strong sense of place are evident. Co-sponsored with the LJAC. Appalachian Lecture."});
				database.add(new String[]{"23","Spring","04/11/13","8:00pm","“Who Could Ask for Anything More?”–An All Gershwin Revue. ","Perfomer:Spectrum Brass","Committed to creative collaboration, Spectrum Brass adds musical layers of piano, percussion,and vocals to their stunning brass arrangements. The audience will be transported to the clubsof NYC in the 1920s and 30s with their engaging and energetic arrangements of Gershwin’s music. A Stephenson Memorial Concert."});
				database.add(new String[]{"24","Spring","04/18/13","3:00pm","Frays in the Social Fabric, Rents in the Commonweal: A Sewing Kit","Speaker: Beverly May","Beverly May is a true Appalachian hero. From her home in Eastern Kentucky on land her family has inhabited for generations, she has successfully fought mountaintop removal mining, started an old-time music school, served as a nurse practitioner, and led the local food movement. Co sponsored with CCC, the LJAC, and the Center for Excellence in Learning through Service (CELTS). Service Convocation"});
														
				// Special ones are hidden currently to show blank convo/no data in the menu. 
				
				// Special convos Fall 2012 and Spring 2013
				//database.add(new String[]{"","Fall","/2/13","6:00pm","fall convo ","speaker","This is a description of the data that will be used"});
				//database.add(new String[]{"","Spring","/2/14","6:00pm","spring convo ","speaker","This is a description of the data that will be used"});
			
			// returns the above list. 			
			return database;
	}
	
	


}